[build]
  # Netlify is already in the 'frontend' directory, so we just run the build.
  command = "npm run build"
  # The 'dist' directory is created inside 'frontend', which is the base directory.
  publish = "dist"

# Enable Netlify Functions
[functions]
  # We must go up one level ('../') to find the 'netlify' folder.
  directory = "../netlify/functions"
  node_bundler = "esbuild"
  [functions.esbuild]
    loader = { ".js" = "jsx" }

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200