[build]
  # Install the function's dependencies first, then build the frontend.
  command = "npm install --prefix ../netlify/functions && npm run build"
  publish = "dist"

# Enable Netlify Functions
[functions]
  # We must go up one level ('../') to find the 'netlify' folder.
  directory = "../netlify/functions"
  node_bundler = "esbuild"
  [functions.esbuild]
    loader = { ".js" = "jsx" }

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200