[build]
  command = "cd frontend; npm run build"
  publish = "frontend/dist"

# Enable Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  [functions.esbuild]
    loader = { ".js" = "jsx" }

# Redirect API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
